### ISSUE TITLE
[AVM Module Issue]: Missing the outputs `APPLICATIONINSIGHTS_CONNECTION_STRING` and `APPLICATIONINSIGHTS_INSTRUMENTATION_KEY`

### ISSUE THREAD

**Issue by Menghua1** [Azure/terraform-azurerm-avm-res-insights-component#25]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Please add the output `APPLICATIONINSIGHTS_CONNECTION_STRING` and `APPLICATIONINSIGHTS_INSTRUMENTATION_KEY`
For example (azd):
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/terraform/core/monitor/applicationinsights/applicationinsights_output.tf#L1
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/terraform/core/monitor/applicationinsights/applicationinsights_output.tf#L11

CC: @jongio and @JFolberth

**Comment by JFolberth** [comment]
@Menghua1  I believe this is a general discussion as by design additional outputs were not provided per the spec: https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tffr2---category-outputs---additional-terraform-outputs

My thoughts behind this was to provide a consistent user experience. Since this is for spec development it would be to leverage the outputted object to grab these prosperities. If not the concern are two things:
- The user will switch from explicitly expecting outputs at the property level for some modules but not otheres
- Secondly when do you draw the line on what is being outputted? Will we expose every field?

I agree these two are common usage for App Insights and if I was developing my own I'd probably expose them; however, want to adhere to the broader spec pattern.

**Comment by v-xuto** [comment]
@Jongio Any ideas on the above [comments](https://github.com/Azure/terraform-azurerm-avm-res-insights-component/issues/25#issuecomment-2180694233)?

**Comment by jongio** [comment]
@JFolberth - Does the outputted object currently include these properties?  If so, then one option would be to shift the extraction of the values to the user.

**Comment by JFolberth** [comment]
Yup it can be referenced by:
`    site_config = {
    "APPLICATIONINSIGHTS_INSTRUMENTATION_KEY": module.app_insights.resource.instrumentation_key
  }`


Confirmed this will work.

I am looping in @Azure/avm-core-team-technical-terraform to keep me honest on pushing for the resource object property piece as I perceived this is related to `azd` development. Would like to ensure a consistent experience for the user and confirming this is the best way to achieve this.

**Comment by JFolberth** [comment]
So I did reach out to the core team on a separate thread. The Terraform AVM guidance has changed as it has been brought to the team's attention that by exporting the entire resource one could inadvertently expose secret values. Thus, the guidance has pivoted to only exposing attributes specifically via the output. 

The output change will introduce a breaking change across almost all of AVM modules, for context linting checks validated if the resource object was an output. I will work this week on adding the outputs and will release a new minor version until hearing more guidance from the team on how to proceed/communicate the breaking one.

**Comment by JFolberth** [comment]
Had a meeting cancel. New version is out there: 

https://registry.terraform.io/modules/Azure/avm-res-insights-component/azurerm/latest

Feel free to provide any feedback/questions.
